### ISSUE TITLE
Issue with french language

### ISSUE THREAD

**Issue by lgerrets** [Tempus/Spire-with-Friends#43]
Hello! First, thanks for this wonderful mod!

On april 2021, this mod was well functionning for me and my 3 friends.

Today, we wanted to try with a new friend. He added the mod because he is the only one who did not have it already. When joining the lobby, then launching, all of our games crash, except for our new friend !

Those that crash get this exact message:

Game crashed.
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-22-2020)
 - ModTheSpire (3.24.0)
Mod list:
 - basemod (5.37.0)
 - chronoMods (2.1)

Cause:
java.lang.ArrayIndexOutOfBoundsException: 1
	at chronoMods.coop.relics.BlueLadder.updateDescription(BlueLadder.java:124)
	at chronoMods.coop.relics.BlueLadder.<init>(BlueLadder.java:113)
	at chronoMods.TogetherManager.receivePostDungeonInitialize(TogetherManager.java:327)
	at basemod.BaseMod.publishPostDungeonInitialize(BaseMod.java:2228)
	at basemod.patches.com.megacrit.cardcrawl.dungeons.AbstractDungeon.PostDungeonInitializeHook.Postfix(PostDungeonInitializeHook.java:9)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.initializeRelicList(AbstractDungeon.java:1650)
	at com.megacrit.cardcrawl.dungeons.Exordium.<init>(Exordium.java:52)
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1379)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:861)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:419)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

The new friend has the same version info and mod list.

We tried :
- uninstalling the mod from the workshop
- manually deleting SteamLibrary\steamapps\workshop\content\646570\2395241968
- reinstalling the mod from the workshop
- still does not work

The reason was that the new friend has the game in english, but us 3 have it in french. The issue was that the flavor text of the blue ladder is an array of just one element, instead of 2 as in the english version. Right now we all switched to english and it works fine ! :)

**Comment by Patschke** [comment]
The issues are not limited to the french localization (and it also seems like not only the blue ladder is malformed, but it's the first point to fail). 

```
$ python checkLocalization.py
INFO:root:Checking validity of json files in ../src/main/resources/chrono/localization/
INFO:root:Checking blights.json:
INFO:root:Checking jpn
ERROR:root:Lists at blights.json->jpn->BlueLadder->DESCRIPTION has wrong length (1 instead of 2)
INFO:root:Checking zhs
ERROR:root:Lists at blights.json->zhs->BlueLadder->DESCRIPTION has wrong length (1 instead of 2)
INFO:root:Checking fra
ERROR:root:Lists at blights.json->fra->BlueLadder->DESCRIPTION has wrong length (1 instead of 2)
INFO:root:Checking eng
INFO:root:No errors found
INFO:root:Checking deu
ERROR:root:Lists at blights.json->deu->BlueLadder->DESCRIPTION has wrong length (1 instead of 2)
INFO:root:Checking ui.json:
INFO:root:Checking jpn
ERROR:root:Lists at ui.json->jpn->NeowRewards->TEXT has wrong length (23 instead of 28)
INFO:root:Checking zhs
ERROR:root:Lists at ui.json->zhs->NeowRewards->TEXT has wrong length (23 instead of 28)
INFO:root:Checking fra
ERROR:root:Lists at ui.json->fra->NeowRewards->TEXT has wrong length (23 instead of 28)
INFO:root:Checking eng
INFO:root:No errors found
INFO:root:Checking deu
ERROR:root:Lists at ui.json->deu->NeowRewards->TEXT has wrong length (23 instead of 28)
```

I can submit a PR to fix those issues?
