### ISSUE TITLE
Crash when creating discord Co-Op lobby

### ISSUE THREAD

**Issue by cjbaskin123** [Tempus/Spire-with-Friends#71]
When I try to open a co-op lobby with the discord integration, it crashes.  I'm using Spire with Friends v3.2 and BaseMod 5.53.2.

I'm not sure if there's some other step I need to complete, I'm including the error log that I was able to get below:

01:48:29.188 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at de.jcm.discordgamesdk.lobby.LobbyMemberTransaction.setMetadata(LobbyMemberTransaction.java:59) ~[Spire%20with%20Friends.jar:?]
	at chronoMods.network.discord.DiscordLobby.setOurMetadata(DiscordLobby.java:222) ~[Spire%20with%20Friends.jar:?]
	at chronoMods.network.discord.DiscordLobby.setUpNetworking(DiscordLobby.java:232) ~[Spire%20with%20Friends.jar:?]
	at chronoMods.network.discord.DiscordIntegration.lambda$createLobby$5(DiscordIntegration.java:293) ~[Spire%20with%20Friends.jar:?]
	at de.jcm.discordgamesdk.Core.runCallbacks(Native Method) ~[Spire%20with%20Friends.jar:?]
	at de.jcm.discordgamesdk.Core.lambda$runCallbacks$2(Core.java:317) ~[Spire%20with%20Friends.jar:?]
	at de.jcm.discordgamesdk.Core.lambda$execute$4(Core.java:372) ~[Spire%20with%20Friends.jar:?]
	at de.jcm.discordgamesdk.Core.execute(Core.java:385) ~[Spire%20with%20Friends.jar:?]
	at de.jcm.discordgamesdk.Core.execute(Core.java:370) ~[Spire%20with%20Friends.jar:?]
	at de.jcm.discordgamesdk.Core.runCallbacks(Core.java:317) ~[Spire%20with%20Friends.jar:?]
	at chronoMods.network.discord.DiscordIntegration.lambda$runCallbacks$0(DiscordIntegration.java:77) ~[Spire%20with%20Friends.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_144]
	at chronoMods.network.discord.DiscordIntegration.runCallbacks(DiscordIntegration.java:77) ~[Spire%20with%20Friends.jar:?]
	at chronoMods.network.discord.DiscordIntegration$DiscordUpdate.Prefix(DiscordIntegration.java:60) ~[Spire%20with%20Friends.jar:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [?:?]
Controllers: removed manager for application, 0 managers active
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at chronoMods.network.discord.DiscordLobby.stopActivity(DiscordLobby.java:262)
	at chronoMods.network.discord.DiscordLobby.leaveLobby(DiscordLobby.java:122)
	at chronoMods.network.NetworkHelper.leaveLobby(NetworkHelper.java:1671)
	at chronoMods.utilities.SavePatching$ForceExitLobby.Prefix(SavePatching.java:87)
	at com.megacrit.cardcrawl.core.CardCrawlGame.dispose(CardCrawlGame.java)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:245)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by Tempus** [comment]
Discord has discontinued this service, sorry.
